### ISSUE TITLE
Null pointer exception with nested namespaced maps

### ISSUE THREAD

**Issue by pedro-w** [borkdude/clj-kondo#11]
When invoking clj-kondo on some code I got a null pointer exception. I have reduced it to a minimal test case

```clj
(ns ck.core
  (:require [ck.it :as it])
  (:gen-class))

(defn -main
  [& args]
  (println #::it {:a #::it {}}))
```

I get the error shown below. I've tried various combinations and it seems the nested use of auto-resolved namespaced keywords triggers it.

Probably related, if I use the current namespace, i.e. `#:: {:a #:: {}}`, I get "[line 7, col 16] A single colon is not a valid keyword."

* Debian GNU/Linux 9.8 (stretch) x64
* Clojure 1.10.0
* openjdk 1.8.0_181

```
$ lein clj-kondo src/ck/core.clj
Exception in thread "main" Syntax error compiling at (/tmp/form-init2114187965721477842.clj:1:73).
	at clojure.lang.Compiler.load(Compiler.java:7647)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at clojure.lang.Namespace.find(Namespace.java:188)
	at clojure.core$find_ns.invokeStatic(core.clj:4130)
	at clojure.core$the_ns.invokeStatic(core.clj:4160)
	at clojure.core$ns_name.invokeStatic(core.clj:4164)
	at clojure.core$ns_name.invoke(core.clj:4164)
	at rewrite_clj.node.seq.NamespacedMapNode.sexpr(seq.clj:57)
	at rewrite_clj.node.protocols$eval231$fn__275$G__237__277.invoke(protocols.clj:9)
	at rewrite_clj.node.protocols$eval231$fn__275$G__236__280.invoke(protocols.clj:9)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1788)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at rewrite_clj.node.seq$map_node$fn__2119.invoke(seq.clj:110)
	at rewrite_clj.node.seq.SeqNode.sexpr(seq.clj:16)
	at rewrite_clj.node.protocols$eval231$fn__275$G__237__277.invoke(protocols.clj:9)
	at rewrite_clj.node.protocols$eval231$fn__275$G__236__280.invoke(protocols.clj:9)
	at clojure.core$map$fn__5851.invoke(core.clj:2753)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.lang.RT.countFrom(RT.java:646)
	at clojure.lang.RT.count(RT.java:639)
	at rewrite_clj.node.seq$assert_namespaced_map_children.invokeStatic(seq.clj:40)
	at rewrite_clj.node.seq$assert_namespaced_map_children.invoke(seq.clj:37)
	at rewrite_clj.node.seq$namespaced_map_node.invokeStatic(seq.clj:115)
	at rewrite_clj.node.seq$namespaced_map_node.invoke(seq.clj:112)
	at rewrite_clj.parser.core$eval2727$fn__2728.invoke(core.clj:123)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at rewrite_clj.reader$read_with_meta.invokeStatic(reader.clj:132)
	at rewrite_clj.reader$read_with_meta.invoke(reader.clj:128)
	at rewrite_clj.parser.core$parse_next.invokeStatic(core.clj:35)
	at rewrite_clj.parser.core$parse_next.invoke(core.clj:33)
	at rewrite_clj.parser.core$parse_delim$fn__2683.invoke(core.clj:43)
	at rewrite_clj.reader$read_repeatedly$fn__1399.invoke(reader.clj:141)
	at clojure.core$repeatedly$fn__6448.invoke(core.clj:5149)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$take_while$fn__5902.invoke(core.clj:2904)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3142)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at rewrite_clj.reader$read_repeatedly.invokeStatic(reader.clj:143)
	at rewrite_clj.reader$read_repeatedly.invoke(reader.clj:137)
	at rewrite_clj.parser.core$parse_delim.invokeStatic(core.clj:44)
	at rewrite_clj.parser.core$parse_delim.invoke(core.clj:39)
	at rewrite_clj.parser.core$eval2751$fn__2752.invoke(core.clj:172)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at rewrite_clj.reader$read_with_meta.invokeStatic(reader.clj:132)
	at rewrite_clj.reader$read_with_meta.invoke(reader.clj:128)
	at rewrite_clj.parser.core$parse_next.invokeStatic(core.clj:35)
	at rewrite_clj.parser.core$parse_next.invoke(core.clj:33)
	at rewrite_clj.parser.core$parse_delim$fn__2683.invoke(core.clj:43)
	at rewrite_clj.reader$read_repeatedly$fn__1399.invoke(reader.clj:141)
	at clojure.core$repeatedly$fn__6448.invoke(core.clj:5149)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$take_while$fn__5902.invoke(core.clj:2904)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3142)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at rewrite_clj.reader$read_repeatedly.invokeStatic(reader.clj:143)
	at rewrite_clj.reader$read_repeatedly.invoke(reader.clj:137)
	at rewrite_clj.parser.core$parse_delim.invokeStatic(core.clj:44)
	at rewrite_clj.parser.core$parse_delim.invoke(core.clj:39)
	at rewrite_clj.parser.core$eval2751$fn__2752.invoke(core.clj:172)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at rewrite_clj.reader$read_with_meta.invokeStatic(reader.clj:132)
	at rewrite_clj.reader$read_with_meta.invoke(reader.clj:128)
	at rewrite_clj.parser.core$parse_next.invokeStatic(core.clj:35)
	at rewrite_clj.parser.core$parse_next.invoke(core.clj:33)
	at rewrite_clj.parser$parse.invokeStatic(parser.clj:13)
	at rewrite_clj.parser$parse.invoke(parser.clj:10)
	at rewrite_clj.parser$parse_all$fn__2768.invoke(parser.clj:18)
	at clojure.core$repeatedly$fn__6448.invoke(core.clj:5149)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$take_while$fn__5902.invoke(core.clj:2904)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:709)
	at clojure.core$next__5371.invokeStatic(core.clj:64)
	at clojure.core$dorun.invokeStatic(core.clj:3142)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clojure.core$doall.invoke(core.clj:3148)
	at rewrite_clj.parser$parse_all.invokeStatic(parser.clj:20)
	at rewrite_clj.parser$parse_all.invoke(parser.clj:15)
	at rewrite_clj.parser$parse_string_all.invokeStatic(parser.clj:35)
	at rewrite_clj.parser$parse_string_all.invoke(parser.clj:32)
	at clj_kondo.core$process_input.invokeStatic(core.clj:95)
	at clj_kondo.core$process_input.invoke(core.clj:87)
	at clj_kondo.core$process_file.invokeStatic(core.clj:105)
	at clj_kondo.core$process_file.invoke(core.clj:102)
	at clojure.core$map$fn__5851.invoke(core.clj:2755)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:531)
	at clojure.core$seq__5387.invokeStatic(core.clj:137)
	at clojure.core$apply.invokeStatic(core.clj:660)
	at clojure.core$mapcat.invokeStatic(core.clj:2783)
	at clojure.core$mapcat.doInvoke(core.clj:2783)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clj_kondo.main$_main.invokeStatic(main.clj:24)
	at clj_kondo.main$_main.doInvoke(main.clj:18)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.Var.invoke(Var.java:388)
	at user$eval140.invokeStatic(form-init2114187965721477842.clj:1)
	at user$eval140.invoke(form-init2114187965721477842.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	... 12 more
```

**Comment by borkdude** [comment]
Thanks for the report!
This goes back to this issue in rewrite-clj:

https://github.com/xsc/rewrite-clj/issues/54

I'll keep an eye on that issue or work around it myself.

For now, I'll print this as an error:

```
$ echo '#::it' | clj -m clj-kondo.main --lint -
<stdin>:0:0: error: Can't read <stdin>, :keyword node expects 2 values. [at line 2, column 1]
```

**Comment by pedro-w** [comment]
Thanks for the swift response. Looks like the rewrite-clj issue should be fixed soon.

**Comment by borkdude** [comment]
@pedro-w Since namespaced keywords don't have any meaning in clj-kondo right now, I made a workaround for it and pushed a new snapshot version to clojars (since you're using leiningen).

**Comment by borkdude** [comment]
It will be solved by this issue: https://github.com/xsc/rewrite-clj/pull/71

**Comment by borkdude** [comment]
I'll consider this fixed for now and I'll reconsider removing the workaround when upgrading rewrite-clj.

**Comment by pedro-w** [comment]
Thanks @borkdude

**Comment by jumarko** [comment]
Found an issue with namespaced maps and args count reporting.
Following is a function which takes 3 args and I pass it 3 args but clj-kondo reports I try to pass 4 args:

```
# In shell
~/Downloads/clj-kondo --lint tmp.clj
tmp.clj:6:1: error: Wrong number of args (4) passed to user/my-fn
linting took 6ms, errors: 1, warnings: 0

# tmp.clj
;;; Doesn't work properly with namespaced maps
(defn my-fn [db-spec id config]
  (println "Saving into db")
  (println "DONE."))
;; => reports 'Wrong number of args (4) ...'
(my-fn
 {}
 1
 #:my-app{:timeout-ms 10000})
```

**Comment by borkdude** [comment]
@jumarko Thanks for reporting. Can you make this into a separate issue? That makes it easier for me to track.

**Comment by borkdude** [comment]
@jumarko Thanks. Improved the workaround. New linux binary here:

https://1054-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.04.08-alpha-SNAPSHOT-linux-amd64.tar.gz

New mac binary here:

https://1053-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.04.08-alpha-SNAPSHOT-macos-amd64.tar.gz

If this works OK, then I'll merge to master.

**Comment by jumarko** [comment]
Seems to work fine with the provided example on my system.
I've also run it on a larger closed-source project and all those
false-positives went away.

Thanks!
