### ISSUE TITLE
Docker image cannot be built on macOS

### ISSUE THREAD

**Issue by pgj** [borkdude/clj-kondo#190]
Building the Docker image fails with the latest `master` branch.

```sh
$ git clone https://github.com/borkdude/clj-kondo
$ cd clj-kondo
$ git rev-parse HEAD
c24f43a5be9af519372d2591520e7f0ebf8575af
$ docker build .
[...]
Compiling clj-kondo.main
Exception in thread "main" Syntax error compiling at (main.clj:24:25).
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3707)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3701)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.compile1(Compiler.java:7730)
	at clojure.lang.Compiler.compile(Compiler.java:7797)
	at clojure.lang.RT.compile(RT.java:415)
	at clojure.lang.RT.load(RT.java:461)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$compile$fn__6829.invoke(core.clj:6136)
	at clojure.core$compile.invokeStatic(core.clj:6136)
	at clj.native_image$build.invokeStatic(native_image.clj:86)
	at clj.native_image$_main.invokeStatic(native_image.clj:95)
	at clj.native_image$_main.doInvoke(native_image.clj:95)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
	at clojure.java.io$fn__11490.invokeStatic(io.clj:288)
	at clojure.java.io$fn__11490.invoke(io.clj:288)
	at clojure.java.io$fn__11392$G__11368__11399.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$slurp.invokeStatic(core.clj:6942)
	at clojure.core$slurp.doInvoke(core.clj:6942)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3702)
	... 27 more
The command '/bin/sh -c GRAALVM_HOME=/opt/graalvm-ce-1.0.0-rc15 clojure -A:native-image --verbose' returned a non-zero code: 1
$ docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by borkdude** [comment]
Hi @pgj,

The Dockerfile was the result of an experiment which I never really finished. As such, this is not (yet) a supported feature. Why would you use Docker if you can just install a binary for Linux, MacOS or Windows directly? If you really have a use case for this, we could fix Docker.

**Comment by borkdude** [comment]
I quickly made a fix for the Dockerfile. Now you can do:

```
docker build . -t clj-kondo
```
and then for example:
```
$ docker run -v $PWD/src:$PWD/src clj-kondo clj-kondo --lint $PWD/src
/Users/Borkdude/Dropbox/dev/clojure/clj-kondo/src/clj_kondo/impl/linters.clj:143:12: warning: redundant do
/Users/Borkdude/Dropbox/dev/clojure/clj-kondo/src/clj_kondo/impl/rewrite_clj_patch.clj:2:14: warning: namespace rewrite-clj.parser.core is required but never used
/Users/Borkdude/Dropbox/dev/clojure/clj-kondo/src/clj_kondo/impl/var_info.clj:3:14: warning: namespace clj-kondo.impl.var-info-gen is required but never used
/Users/Borkdude/Dropbox/dev/clojure/clj-kondo/src/clj_kondo/main.clj:5:5: warning: namespace clj-kondo.impl.rewrite-clj-patch is required but never used
linting took 549ms, errors: 0, warnings: 4
```

**Comment by pgj** [comment]
I am working on integrating `clj-kondo` into a Jenkins pipeline where Docker images are used.  I have already written up a `Dockerfile` similar to your solution, I just opened this issue because I thought I am doing something wrong and there is a better way to solve the problem.

**Comment by borkdude** [comment]
@pgj Instructions updated at https://github.com/borkdude/clj-kondo/blob/master/doc/install.md#docker

**Comment by borkdude** [comment]
Fixed with 8c1259443abe0848c589996754a3f94b7f6b8dc9

**Comment by pgj** [comment]
Thanks @borkdude it works perfectly.

**Comment by borkdude** [comment]
@pgj Cool. I'll add version tags, so you can depend on a "stable" release in the future.
