### ISSUE TITLE
crash when linting non-existent file + JSON output

### ISSUE THREAD

**Issue by marcomorain** [borkdude/clj-kondo#251]
I got a crash running against a file name that is invalid:

`clj-kondo --config '{:output {:format :json}}' --lint 'extension-output-#5'`

**version**
`clj-kondo v2019.06.07-alpha`

**platform**

`Darwin blaster.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

**problem**

A crash report is attached.

**repro**

`clj-kondo --config '{:output {:format :json}}' --lint 'extension-output-#5'`

**actual behavior**

```
Extension loaded
Extension running
Linted /Users/marc/dev/marcomorain/clojure-lint/src/test/errors.clj: 1 errors, 1 warnings
Linted /Users/marc/dev/marcomorain/clojure-lint/src/test/errors.clj: 1 errors, 1 warnings
Failed to execute clj-kondo
{ error:
   { Error: Command failed: clj-kondo --config {:output {:format :json}} --lint extension-output-#5
   java.lang.NullPointerException
   	at clojure.core$name.invokeStatic(core.clj:1595)
   	at clj_kondo.core$print_BANG_$fn__4361.invoke(core.clj:53)
   	at clojure.core$map$fn__5851.invoke(core.clj:2753)
   	at clojure.lang.LazySeq.sval(LazySeq.java:42)
   	at clojure.lang.LazySeq.seq(LazySeq.java:51)
   	at clojure.lang.LazySeq.first(LazySeq.java:73)
   	at clojure.lang.RT.first(RT.java:688)
   	at clojure.core$first__5369.invokeStatic(core.clj:55)
   	at clojure.string$join.invokeStatic(string.clj:180)
   	at clj_kondo.core$print_BANG_.invokeStatic(core.clj:37)
   	at clj_kondo.main$main.invokeStatic(main.clj:85)
   	at clj_kondo.main$main.doInvoke(main.clj:72)
   	at clojure.lang.RestFn.applyTo(RestFn.java:137)
   	at clojure.core$apply.invokeStatic(core.clj:665)
   	at clj_kondo.main$_main$fn__5626.invoke(main.clj:98)
   	at clj_kondo.main$_main.invokeStatic(main.clj:98)
   	at clj_kondo.main$_main.doInvoke(main.clj:96)
   	at clojure.lang.RestFn.applyTo(RestFn.java:137)
   	at clj_kondo.main.main(Unknown Source)
   
   	at ChildProcess.exithandler (child_process.js:303:12)
   	at ChildProcess.emit (events.js:182:13)
   	at maybeClose (internal/child_process.js:961:16)
   	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
     killed: false,
     code: 124,
     signal: null,
     cmd:
      'clj-kondo --config {:output {:format :json}} --lint extension-output-#5' },
  stdout: '{Unexpected error. Please report an issue.\n',
  stderr:
   'java.lang.NullPointerException\n\tat clojure.core$name.invokeStatic(core.clj:1595)\n\tat clj_kondo.core$print_BANG_$fn__4361.invoke(core.clj:53)\n\tat clojure.core$map$fn__5851.invoke(core.clj:2753)\n\tat clojure.lang.LazySeq.sval(LazySeq.java:42)\n\tat clojure.lang.LazySeq.seq(LazySeq.java:51)\n\tat clojure.lang.LazySeq.first(LazySeq.java:73)\n\tat clojure.lang.RT.first(RT.java:688)\n\tat clojure.core$first__5369.invokeStatic(core.clj:55)\n\tat clojure.string$join.invokeStatic(string.clj:180)\n\tat clj_kondo.core$print_BANG_.invokeStatic(core.clj:37)\n\tat clj_kondo.main$main.invokeStatic(main.clj:85)\n\tat clj_kondo.main$main.doInvoke(main.clj:72)\n\tat clojure.lang.RestFn.applyTo(RestFn.java:137)\n\tat clojure.core$apply.invokeStatic(core.clj:665)\n\tat clj_kondo.main$_main$fn__5626.invoke(main.clj:98)\n\tat clj_kondo.main$_main.invokeStatic(main.clj:98)\n\tat clj_kondo.main$_main.doInvoke(main.clj:96)\n\tat clojure.lang.RestFn.applyTo(RestFn.java:137)\n\tat clj_kondo.main.main(Unknown Source)\n' }
```

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/a395e84428b330749c95483ae22acc0f1d8f7e21
