### ISSUE TITLE
java.lang.IllegalStateException: Can't pop empty vector

### ISSUE THREAD

**Issue by lenw** [borkdude/clj-kondo#317]
**version**

v2019.06.29-alpha

**platform**

Linux

**problem**

`clj-kondo --lint "$(lein classpath)" --cache `

Generates the following error 

**repro**

not sure 

**expected behavior**

Command should finish and build the cache

**actual behavior**

```java.lang.IllegalStateException: Can't pop empty vector
        at clojure.lang.PersistentVector.pop(PersistentVector.java:470)
        at clojure.lang.PersistentVector.pop(PersistentVector.java:22)
        at clojure.lang.RT.pop(RT.java:755)
        at clojure.core$pop.invokeStatic(core.clj:1474)
        at clj_kondo.impl.linters$show_arities.invokeStatic(linters.clj:141)
        at clj_kondo.impl.linters$arity_error.invokeStatic(linters.clj:150)
        at clj_kondo.impl.linters$lint_calls$iter__2237__2247$fn__2248$iter__2239__2249$fn__2250$iter__2241__2251$fn__2252.invoke(linters.clj:214)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clj_kondo.impl.linters$lint_calls$iter__2237__2247$fn__2248$iter__2239__2249$fn__2250.invoke(linters.clj:158)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5402.invokeStatic(core.clj:137)
        at clojure.core$concat$fn__5493.invoke(core.clj:725)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
        at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5386.invokeStatic(core.clj:64)
        at clojure.core$dorun.invokeStatic(core.clj:3142)
        at clojure.core$doall.invokeStatic(core.clj:3148)
        at clj_kondo.core$run_BANG_.invokeStatic(core.clj:94)
        at clj_kondo.main$main.invokeStatic(main.clj:75)
        at clj_kondo.main$main.doInvoke(main.clj:68)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clj_kondo.main$_main$fn__3500.invoke(main.clj:94)
        at clj_kondo.main$_main.invokeStatic(main.clj:94)
        at clj_kondo.main$_main.doInvoke(main.clj:92)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clj_kondo.main.main(Unknown Source)
```

**Comment by borkdude** [comment]
This is probably a duplicate of https://github.com/borkdude/clj-kondo/issues/314. Can you try with this new binary or with `clj` (link in the mentioned issue).

https://4247-176829714-gh.circle-artifacts.com/0/release/clj-kondo-2019.06.30-alpha-SNAPSHOT-linux-amd64.zip

**Comment by lenw** [comment]
New binary works and yes looks like a dupe, closing this and thanks for the assist. Noce tool :+1:
