### ISSUE TITLE
Local type checking / inference

### ISSUE THREAD

**Issue by borkdude** [borkdude/clj-kondo#445]
```
$ echo '(reverse (map inc))' | clj -A:clj-kondo --lint -
<stdin>:1:10: error: Expected: seqable collection, received: transducer.
linting took 130ms, errors: 1, warnings: 0
```

TODO:

- [x] handle cases in performance.txt output
- [x] take type hints on function arguments into account
- [x] take function return types into account
- [x] use type hints on function arguments also when calling the function (not only inside the definition)
- [x] handle multiple spec errors in one error message
- [x] clean up :arities vs :fixed-arities duplication
- [x] clean up types ns
- [x] write docs

**Comment by sogaiu** [comment]
Ran:

```
$ clj-kondo --lint clojure | grep Expected
```

through clojure's source and got roughly:

```
clojure/test/clojure/test_clojure/data_structures.clj:1130:44: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/logic.clj:109:14: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/sequences.clj:110:16: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/sequences.clj:173:49: error: Expected: seqable collection, received: positive integer.
clojure/test/clojure/test_clojure/sequences.clj:175:13: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/sequences.clj:176:15: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/sequences.clj:178:14: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/sequences.clj:822:14: error: Expected: seqable collection, received: nil.
clojure/test/clojure/test_clojure/serialization.clj:55:13: error: Expected: seqable collection, received: nil.
```

I think the first one corresponds to:

```
(deftest ordered-collection-equality-test
  (let [empty-colls [ []
                      '()
                      (lazy-seq)
                      clojure.lang.PersistentQueue/EMPTY
                      (vector-of :long) ]]
    (doseq [c1 empty-colls, c2 empty-colls]
      (is-same-collection c1 c2)))
  (let [colls1 [ [-3 :a "7th"]
                 '(-3 :a "7th")
                 (lazy-seq (cons -3
                   (lazy-seq (cons :a
                     (lazy-seq (cons "7th" nil)))))) ; <-------- this line is 1130
                 (into clojure.lang.PersistentQueue/EMPTY
                       [-3 :a "7th"])
                 (sequence (map identity) [-3 :a "7th"]) ]]
    (doseq [c1 colls1, c2 colls1]
      (is-same-collection c1 c2)))
  (is-same-collection [-3 1 7] (vector-of :long -3 1 7)))
```

**Comment by sogaiu** [comment]
Not sure if I'm doing this right, but FWIW:

git clone https://github.com/clojure/tools.reader && cd tools.reader

```
$ clj-kondo --lint . | grep Expected
java.lang.IllegalArgumentException: No matching clause: [:clj :edn]
	at clj_kondo.impl.linters$resolve_call_STAR_.invokeStatic(linters.clj:125)
	at clj_kondo.impl.linters$resolve_call.invokeStatic(linters.clj:141)
	at clj_kondo.impl.linters$lint_var_usage$iter__4830__4838$fn__4839$iter__4832__4840$fn__4841.invoke(linters.clj:199)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clj_kondo.impl.linters$lint_var_usage$iter__4830__4838$fn__4839.invoke(linters.clj:188)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5402.invokeStatic(core.clj:137)
	at clojure.core$dorun.invokeStatic(core.clj:3133)
	at clojure.core$doall.invokeStatic(core.clj:3148)
	at clj_kondo.core$run_BANG_.invokeStatic(core.clj:97)
	at clj_kondo.main$main.invokeStatic(main.clj:85)
	at clj_kondo.main$main.doInvoke(main.clj:78)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clj_kondo.main$_main$fn__5793.invoke(main.clj:104)
	at clj_kondo.main$_main.invokeStatic(main.clj:104)
	at clj_kondo.main$_main.doInvoke(main.clj:102)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clj_kondo.main.main(Unknown Source)
```

**Comment by borkdude** [comment]
@sogaiu Both problems should be fixed. I forgot that `nil` is also seqable.

The error:

```
clojure/test/clojure/test_clojure/sequences.clj:173:49: error: Expected: seqable collection, received: positive integer.
```
came from `(cons 1 2)` in a test, so that's good news :).
