### ISSUE TITLE
clj-kondo fails with `No maching field found: getMessage for class java.lang.NullPointerException` when initializing cache

### ISSUE THREAD

**Issue by jumarko** [borkdude/clj-kondo#61]
I've just installed clj-kondo via homebrew on my Mac OS X (10.14.3) and tried to run it on a closed-source project (fairly non-trivial with lots of dependencies) but cache initialization fails after a while with the following error:

```
$ clj-kondo --version
clj-kondo v2019.04.07-alpha

$ clj-kondo --lint $(lein classpath) --cache
...
Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: getMessage for class java.lang.NullPointerException
        at clojure.lang.Reflector.getInstanceField(Reflector.java:397)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:440)
        at clojure.stacktrace$print_throwable.invokeStatic(stacktrace.clj:43)
        at clojure.stacktrace$print_stack_trace.invokeStatic(stacktrace.clj:55)
        at clojure.stacktrace$print_stack_trace.invoke(stacktrace.clj:48)
        at clojure.stacktrace$print_stack_trace.invokeStatic(stacktrace.clj:53)
        at clojure.stacktrace$print_stack_trace.invoke(stacktrace.clj:48)
        at clj_kondo.main$_main$fn__4224.invoke(main.clj:269)
        at clj_kondo.main$_main.invokeStatic(main.clj:267)
        at clj_kondo.main$_main.doInvoke(main.clj:265)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clj_kondo.main.main(Unknown Source)
```

I tried the same on my [clojure-experiments](https://github.com/jumarko/clojure-experiments) public project and it fails again with the same error

I've tried both Java 8 and Java 11 => the same result.

I've got a bunch of extra dependencies in my ~/.lein/profiles.clj so I thought they may affect it too.
However, I ran this using only _base_ lein profile and the result is again the same:
```
clj-kondo --lint $(lein with-profile base classpath) --cache

WARNING!!! version ranges found for:
[net.cgrand/sjacket "0.1.1"] -> [org.clojure/clojure "[1.3.0,)"]
Consider using [net.cgrand/sjacket "0.1.1" :exclusions [org.clojure/clojure]].
[net.cgrand/sjacket "0.1.1"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [net.cgrand/sjacket "0.1.1" :exclusions [org.clojure/clojure]].
[net.cgrand/sjacket "0.1.1"] -> [net.cgrand/parsley "0.9.2"] -> [net.cgrand/regex "1.1.0"] -> [org.clojure/clojure "[1.2.0,)"]
Consider using [net.cgrand/sjacket "0.1.1" :exclusions [org.clojure/clojure]].

Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: getMessage for class java.lang.NullPointerException
        at clojure.lang.Reflector.getInstanceField(Reflector.java:397)
        at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:440)
        at clojure.stacktrace$print_throwable.invokeStatic(stacktrace.clj:43)
        at clojure.stacktrace$print_stack_trace.invokeStatic(stacktrace.clj:55)
        at clojure.stacktrace$print_stack_trace.invoke(stacktrace.clj:48)
        at clojure.stacktrace$print_stack_trace.invokeStatic(stacktrace.clj:53)
        at clojure.stacktrace$print_stack_trace.invoke(stacktrace.clj:48)
        at clj_kondo.main$_main$fn__4224.invoke(main.clj:269)
        at clj_kondo.main$_main.invokeStatic(main.clj:267)
        at clj_kondo.main$_main.doInvoke(main.clj:265)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clj_kondo.main.main(Unknown Source)
```

**Comment by borkdude** [comment]
Three issues:

Cannot use clojure.stracktrace/print-stack-trace with GraalVM: https://dev.clojure.org/jira/browse/CLJ-2502
So I'll drop back to Java `.printStackTrace` for now.

Second issue was a NullPointer exception: `inc` used on null when producing the summary.
I'll fix that as well.

Third issue: clj-kondo has trouble parsing the defn forms in https://github.com/tonsky/datascript/blob/master/src/datascript/db.cljc#L34. clj-kondo handles this gracefully by just ignoring them, but I'll take a look why this is the case.

**Comment by borkdude** [comment]
@jumarko Thanks for the report and trying out clj-kondo.
Are you on Linux or Mac? I'll point you to a binary with the fix included, so you can test it.

**Comment by jumarko** [comment]
@borkdude thanks for the super-fast response!
I can confirm that the cache initialization now works fine.

**Comment by borkdude** [comment]
Fixed with https://github.com/borkdude/clj-kondo/commit/bf141734f7fb0079740ebfa30ef3337c2d0a0e3b
